### ISSUE TITLE
Issue with lsdb.read_hipscat on URL

### ISSUE THREAD

**Issue by JoaoDPassos** [astronomy-commons/lsdb#380]
Hello, 

When running the following code, `catalog = lsdb.read_hipscat(https://epyc.astro.washington.edu/~lincc-frameworks/hipscat_surveys/des/des_dr2/)`, I got the error somewhere along the lines of "could not find /des/des_dr2/hipscat/catalog_info.json" (apologies I forgot the entire error message and could not replicate the issue). Taking inspiration from the following stackoverflow post: https://stackoverflow.com/questions/69605350/aiohttp-raises-an-certificate-error-with-some-sites-that-browser-opens-normally, I imported the certifi python library and the code ran as expected. It should be said that the link did include a catalog_info.json file at the correct path, so we assumed this error message was unrelated to the actual problem which we thought to be a certificate problem. This was ran on macos 13.5, python 3.11.7, and lsdb 0.2.6.

**Comment by camposandro** [comment]
Hi @JoaoDPassos, I tried reading the catalog on that same LSDB version, python 3.11.9 and it ran smoothly. Do you have `aiohttp` installed in your environment (`$ pip show aiohttp`)? It should be automatically installed by hipscat; mine is version 3.9.5. Also, please try with `lsdb.read_hipscat('https://data.lsdb.io/unstable/des/des_dr2')` and if the error persists, could you please recreate your environment from scratch and send the full error message? Thanks!

**Comment by hombit** [comment]
@camposandro  `aiohttp` was installed, but it gave `FileNotFound` because of the missed certificates. This problem could be hard to reproduce on Mac, because if you have installed certificates once you already have them, but here a reproducible example with docker

```sh
docker build --tag lsst-380 .
docker run lsst-380
```

```Dockerfile
FROM python:3.11

RUN pip install lsdb aiohttp

RUN apt-get prune ca-certificates

CMD ["python", "-c", "import lsdb; lsdb.read_hipscat('https://epyc.astro.washington.edu/~lincc-frameworks/hipscat_surveys/des/des_dr2/')"]
```

<details><summary>Traceback</summary>

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1025, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1113, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1146, in _create_connection_transport
    await waiter
  File "/usr/local/lib/python3.11/asyncio/sslproto.py", line 578, in _on_handshake_complete
    raise handshake_exc
  File "/usr/local/lib/python3.11/asyncio/sslproto.py", line 560, in _do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.11/ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/fsspec/implementations/http.py", line 422, in _info
    await _file_info(
  File "/usr/local/lib/python3.11/site-packages/fsspec/implementations/http.py", line 832, in _file_info
    r = await session.get(url, allow_redirects=ar, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1257, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1226, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1027, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host epyc.astro.washington.edu:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/lsdb/loaders/hipscat/read_hipscat.py", line 79, in read_hipscat
    catalog_type_to_use = _get_dataset_class_from_catalog_info(path, storage_options=storage_options)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/lsdb/loaders/hipscat/read_hipscat.py", line 93, in _get_dataset_class_from_catalog_info
    catalog_info = BaseCatalogInfo.read_from_metadata_file(catalog_info_path, storage_options=storage_options)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hipscat/catalog/dataset/base_catalog_info.py", line 60, in read_from_metadata_file
    metadata_keywords = file_io.load_json_file(catalog_info_file, storage_options=storage_options)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hipscat/io/file_io/file_io.py", line 128, in load_json_file
    with file_system.open(file_pointer, "r", encoding=encoding) as json_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fsspec/spec.py", line 1291, in open
    self.open(
  File "/usr/local/lib/python3.11/site-packages/fsspec/spec.py", line 1303, in open
    f = self._open(
        ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fsspec/implementations/http.py", line 361, in _open
    size = size or self.info(path, **kwargs)["size"]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fsspec/asyn.py", line 118, in wrapper
    return sync(self.loop, func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fsspec/asyn.py", line 103, in sync
    raise return_result
  File "/usr/local/lib/python3.11/site-packages/fsspec/asyn.py", line 56, in _runner
    result[0] = await coro
                ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fsspec/implementations/http.py", line 435, in _info
    raise FileNotFoundError(url) from exc
FileNotFoundError: https://epyc.astro.washington.edu/~lincc-frameworks/hipscat_surveys/des/des_dr2/catalog_info.json
```

</details>

**Comment by hombit** [comment]
The actionable item can be docs update, either installation instructions or a new FAQ/troubleshooting page telling what additional steps user need to do to access remote data.

For HTTPS we could tell that
1. `pip install aiohttp` / `conda install aiohttp`
2. If see `FileNotFoundError`
  a. Check your network and server availability
  b. On Linux be sure that openSSL and ca-certificates are on place
  c. On Mac run `/Applications/Python\ 3.*/Install\ Certificates.command`

**Comment by camposandro** [comment]
@hombit your suggestions seem to have been completed by @delucchi-cmu in https://github.com/astronomy-commons/lsdb/pull/413.

**Comment by hombit** [comment]
I believe the documentation part of the issue is still valid: the Docker example still fails

**Comment by camposandro** [comment]
I believe it's already in the latest version of the documentation, under [Remote Data](https://docs.lsdb.io/en/latest/tutorials/remote_data.html).
