### ISSUE TITLE
`to_hipscat` doesn't work when one partition is empty

### ISSUE THREAD

**Issue by smcguire-cmu** [astronomy-commons/lsdb#93]
When running `gaia.cone_search(10,10,0.5).to_hipscat(...)` I get the following error:

```
RuntimeError: AppendRowGroups requires equal schemas.
The two columns with index 1 differ.
column descriptor = {
  name: designation,
  path: designation,
  physical_type: BYTE_ARRAY,
  converted_type: UTF8,
  logical_type: String,
  max_definition_level: 1,
  max_repetition_level: 0,
}
column descriptor = {
  name: designation,
  path: designation,
  physical_type: INT32,
  converted_type: NONE,
  logical_type: Null,
  max_definition_level: 1,
  max_repetition_level: 0,
}
```

with the end of the stack trace:

```
File ~/hipscat_deploy/src/hipscat/io/file_io/file_io.py:261, in write_parquet_metadata(schema, file_pointer, metadata_collector, storage_options, **kwargs)
    258 file_system, file_pointer = get_fs(file_pointer=file_pointer, storage_options=storage_options)
    260 file_pointer = strip_leading_slash_for_pyarrow(file_pointer, protocol=file_system.protocol)
--> 261 pq.write_metadata(
    262     schema, file_pointer, metadata_collector=metadata_collector, filesystem=file_system, **kwargs
    263 )

File ~/anaconda3/envs/lsdb/lib/python3.9/site-packages/pyarrow/parquet/core.py:3555, in write_metadata(schema, where, metadata_collector, filesystem, **kwargs)
   3552     where.seek(cursor_position)  # file-like, set cursor back.
   3554 for m in metadata_collector:
-> 3555     metadata.append_row_groups(m)
   3556 if filesystem is not None:
   3557     with filesystem.open_output_stream(where) as f:

File ~/anaconda3/envs/lsdb/lib/python3.9/site-packages/pyarrow/_parquet.pyx:799, in pyarrow._parquet.FileMetaData.append_row_groups()
```

I believe this is because the metadata collector gets different types for the different files because one is empty.

**Comment by camposandro** [comment]
@smcguire-cmu, I ran `to_hipscat` on the same cone search catalog and the output catalog was created successfully even though there's an empty data partition. The partition info is the following:

```csv
Norder,Dir,Npix,num_rows
2,0,76,2440
2,0,77,0
```

I noticed however that hipscat fails to read the catalog later on because the empty partition does not contain any metadata statistics. I have tested both the `strict` and `non-strict` alternatives.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lsdb/loaders/hipscat/read_hipscat.py", line 60, in read_hipscat
    return loader.load_catalog()
  File ".../lsdb/loaders/hipscat/hipscat_catalog_loader.py", line 41, in load_catalog
    hc_catalog = self.load_hipscat_catalog()
  File ".../lsdb/loaders/hipscat/hipscat_catalog_loader.py", line 47, in load_hipscat_catalog
    return hc.catalog.Catalog.read_from_hipscat(self.path, storage_options=self.storage_options)
  File ".../hipscat/catalog/dataset/dataset.py", line 60, in read_from_hipscat
    args = cls._read_args(catalog_base_dir, storage_options=storage_options)
  File ".../hipscat/catalog/healpix_dataset/healpix_dataset.py", line 89, in _read_args
    partition_info = PartitionInfo.read_from_file(metadata_file, storage_options=storage_options)
  File ".../hipscat/catalog/partition_info.py", line 119, in read_from_file
    pixel_list = [
  File ".../hipscat/catalog/partition_info.py", line 121, in <listcomp>
    total_metadata.row_group(index).column(norder_column).statistics.min,
AttributeError: 'NoneType' object has no attribute 'min'
```
